name: Build Programs

on:
  workflow_call:
    inputs:
      rust:
        type: string
      solana:
        type: string
  workflow_dispatch:
    inputs:
      rust:
        description: Rust version
        default: 1.87.0
        required: true
        type: string
      solana:
        description: Solana version
        default: 2.2.14
        required: true
        type: string

env:
  CACHE: true
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"

jobs:
  build_programs:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Rust
        uses: nifty-oss/actions/install-rust@v1
        with:
          toolchain: ${{ inputs.rust || env.RUST_VERSION }}

      - name: Install Solana
        uses: ./.github/actions/install-solana
        with:
          version: ${{ inputs.solana || env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Install Node for running zx
        uses: nifty-oss/actions/install-node-with-pnpm@v1
        with:
          folder: ./clients/js
          cache: ${{ env.CACHE }}
          key: client-js

      - name: Install Node root dependencies
        uses: nifty-oss/actions/install-node-dependencies@v1
        with:
          folder: "."
          cache: ${{ env.CACHE }}
          key: client-js

      - name: Install Node dependencies
        uses: nifty-oss/actions/install-node-dependencies@v1
        with:
          folder: ./clients/js
          cache: ${{ env.CACHE }}
          key: client-js

      - name: Install zx
        run: npm install -g zx

      - name: Cache program dependencies
        if: env.CACHE == 'true'
        uses: ./.github/actions/cache-crate
        with:
          folder: "."
          key: programs

      - name: Build programs
        shell: bash
        working-directory: "."
        run: npx zx ./scripts/program/build.mjs
        env:
          PROGRAMS: ${{ env.PROGRAMS }}

      - name: Upload program builds
        uses: actions/upload-artifact@v4
        with:
          name: program-builds
          # First wildcard ensures exported paths are consistently under the programs folder.
          path: ./targe*/deploy/*.so
          if-no-files-found: error
