name: Build Rust Client

on:
  workflow_call:
    inputs:
      rust:
        type: string
      solana:
        type: string
  workflow_dispatch:
    inputs:
      rust:
        description: Rust version
        default: 1.84.1
        required: true
        type: string
      solana:
        description: Solana version
        default: 2.2.14
        required: true
        type: string

env:
  CACHE: true
  CARGO_NET_GIT_FETCH_WITH_CLI: 'true'

jobs:
  build_sdk:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Rust
        uses: nifty-oss/actions/install-rust@v1
        with:
          toolchain: ${{ inputs.rust || env.RUST_VERSION }}

      - name: Install Solana
        uses: solana-program/actions/install-solana@v1
        with:
          version: ${{ inputs.solana || env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Cache Rust client test dependencies
        uses: ./.github/actions/cache-crate
        with:
          folder: ./clients/rust
          key: rust-client-test

      - name: Run cargo clippy
        uses: nifty-oss/actions/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features --no-deps --manifest-path ./clients/rust/Cargo.toml

      - name: Build Rust client
        shell: bash
        working-directory: clients/rust
        run: cargo build --all-features --release

      - name: Upload Rust client builds
        uses: actions/upload-artifact@v4
        with:
          name: rust-client-builds
          # First wildcard ensures exported paths are consistently under the clients folder.
          path: ./targe*/release/*sigil_client*
          if-no-files-found: error
