name: Test Programs

on:
  workflow_call:
    inputs:
      program_matrix:
        type: string

env:
  CACHE: true
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"

jobs:
  test_programs:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        program: ${{ fromJson(inputs.program_matrix) }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Rust
        uses: nifty-oss/actions/install-rust@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Install Solana
        uses: ./.github/actions/install-solana
        with:
          version: ${{ env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Install Node for running zx
        uses: nifty-oss/actions/install-node-with-pnpm@v1
        with:
          folder: ./clients/js
          cache: ${{ env.CACHE }}
          key: client-js

      - name: Install Node root dependencies
        uses: nifty-oss/actions/install-node-dependencies@v1
        with:
          folder: "."
          cache: ${{ env.CACHE }}
          key: client-js

      - name: Install Node dependencies
        uses: nifty-oss/actions/install-node-dependencies@v1
        with:
          folder: ./clients/js
          cache: ${{ env.CACHE }}
          key: client-js

      - name: Install zx
        run: npm install -g zx

      - name: Cache program dependencies
        if: env.CACHE == 'true'
        uses: nifty-oss/actions/cache-crate@v1
        with:
          folder: "."
          key: programs

      - name: Run cargo fmt
        uses: nifty-oss/actions/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path ./${{ matrix.program }}/Cargo.toml -- --check

      - name: Run cargo clippy
        uses: nifty-oss/actions/cargo@v1
        with:
          command: clippy
          args:
            --all-targets --all-features --no-deps --manifest-path ./${{ matrix.program
            }}/Cargo.toml

      - name: Run tests
        shell: bash
        working-directory: "."
        run: RUST_LOG=error npx zx ./scripts/program/test.mjs
        env:
          PROGRAM: ${{ matrix.program }}
